# Generated by Django 3.1.1 on 2020-10-20 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1024, verbose_name='key')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'm_user',
            },
        ),
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2048, null=True, verbose_name='原始url')),
                ('short_code', models.CharField(max_length=15, null=True, verbose_name='缩短码')),
                ('is_active', models.BooleanField(default=True, null=True, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortUrl2UserId', to='app.user', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '短链接表',
                'verbose_name_plural': '短链接表',
                'db_table': 'm_shorturl',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.CharField(max_length=2048, null=True, verbose_name='文本内容')),
                ('file_url', models.CharField(max_length=2048, null=True, verbose_name='文件地址')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('type', models.CharField(choices=[('0', '文本'), ('1', '文件')], default='0', max_length=255, verbose_name='类型')),
                ('is_delete', models.CharField(choices=[('0', '生效中'), ('1', '已删除')], default='0', max_length=255, verbose_name='是否生效')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userId', to='app.user', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '记录表',
                'verbose_name_plural': '记录表',
                'db_table': 'm_record',
            },
        ),
    ]
