# Generated by Django 3.1.1 on 2020-10-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='is_delete',
            field=models.BooleanField(default=False, null=True, verbose_name='是否已删除'),
        ),
    ]
